spring:
  application:
    name: edm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: public
  data:
    rest:
      base-path: edm-data
  datasource:
    url: jdbc:postgresql://localhost:5432/edmdb
    username: postgres
    password: postgres